# Deployment environment name, typically the name of the deployment or project.
DEPLOYMENT_ENV_NAME=""  # Example: "privacera-prod" or "privacera-dev"

# Docker image for Privacera Manager. It includes the repository URL and the image tag.
PRIV_MGR_IMAGE=""  # Example: "hub2.privacera.com/privacera-manager:rel_9.0.0.3"

# URL for the Privacera Manager package, usually hosted on an S3 bucket or a similar repository.
PRIV_MGR_PACKAGE=""  # Example: "https://privacera-host/path/privacera-manager.tar.gz"

# Username for accessing Privacera Hub, the central repository for Privacera images.
PRIVACERA_HUB_USER=""  # Example: "hub_user"

# Password for accessing Privacera Hub. This should be securely stored.
PRIVACERA_HUB_PASSWORD=""  # Example: "hub_password"

# Password for Ansible Vault, used to encrypt and decrypt sensitive Ansible variables in the EC2 instance.
ANSIBLE_VAULT_PASSWORD=""  # Use a strong password. Don't forget to store it securely. This is not recoverable.

# Password for the global secrets keystore. Used to encrypt sensitive information in the Pod
GLOBAL_DEFAULT_SECRETS_KEYSTORE_PASSWORD=""  # Use a strong password

# Default password for SSL certificate management. This should be a strong password.
SSL_DEFAULT_PASSWORD=""  # This is used secure the SSL certificates generated by the Privacera Manager.

# Database configuration
# Uncomment the appropriate database type you are using:
#DB=MYSQL     # For MySQL Database
#DB=POSTGRESQL  # For PostgreSQL Database
#DB=NATIVE     # For the internal database

# Hostname or IP address of the external database.
EXTERNAL_DB_HOST=""  # Example: "database.example.com" or "192.168.1.100"

# Name of the external database.
EXTERNAL_DB_NAME=""  # Example: "privacera_db"

# Username for accessing the external database.
EXTERNAL_DB_USER=""  # Example: "db_admin"

# Password for the external database user. This should be stored securely.
EXTERNAL_DB_PASSWORD=""  # Example: "YourSecureDBPassword"

# Port number for the external database (Optional). Uncomment and set value if needed.
# EXTERNAL_DB_PORT=""  # Example: "3306" for MySQL or "5432" for PostgreSQL