# Deployment environment name, typically the name of the deployment or project.
DEPLOYMENT_ENV_NAME=""  # Example: "privacera-prod" or "privacera-dev"

# Docker image for Privacera Manager. It includes the repository URL and the image tag.
PRIV_MGR_IMAGE=""  # Example: "hub2.privacera.com/privacera-manager:rel_9.0.0.3"

# URL for the Privacera Manager package, usually hosted on an S3 bucket or a similar repository.
PRIV_MGR_PACKAGE=""  # Example: "https://privacera-host/path/privacera-manager.tar.gz"

# Username for accessing Privacera Hub, the central repository for Privacera images.
PRIVACERA_HUB_USER=""  # Example: "hub_user"

# Password for accessing Privacera Hub. This should be securely stored.
PRIVACERA_HUB_PASSWORD=""  # Example: "hub_password"

# Password for Ansible Vault, used to encrypt and decrypt sensitive Ansible variables in the EC2 instance.
ANSIBLE_VAULT_PASSWORD=""  # Use a strong password. Don't forget to store it securely. This is not recoverable.

# Password for the global secrets keystore. Used to encrypt sensitive information in the Pod
GLOBAL_DEFAULT_SECRETS_KEYSTORE_PASSWORD=""  # Use a strong password

# AWS region where the deployment will occur.
AWS_REGION=""  # Example: "us-east-1"

# Elastic File System (EFS) File System ID for shared storage in AWS.
EFS_FSID=""  # Example: "fs-1234567890abcdef"

# Default password for SSL certificate management. This should be a strong password.
SSL_DEFAULT_PASSWORD=""  # This is used secure the SSL certificates generated by the Privacera Manager.

# Database configuration
# Uncomment the appropriate database type you are using:
#DB=MYSQL     # For MySQL Database
#DB=POSTGRESQL  # For PostgreSQL Database
#DB=NATIVE     # For the internal database

# Hostname or IP address of the external database.
EXTERNAL_DB_HOST=""  # Example: "database.example.com" or "192.168.1.100"

# Name of the external database.
EXTERNAL_DB_NAME=""  # Example: "privacera_db"

# Username for accessing the external database.
EXTERNAL_DB_USER=""  # Example: "db_admin"

# Password for the external database user. This should be stored securely.
EXTERNAL_DB_PASSWORD=""  # Example: "YourSecureDBPassword"

# Port number for the external database (Optional). Uncomment and set value if needed.
# EXTERNAL_DB_PORT=""  # Example: "3306" for MySQL or "5432" for PostgreSQL

# Domain name for AWS Route 53. If Privacera will create Route 53 entries. The service name will be prefixed with this domain.
AWS_ROUTE_53_DOMAIN_NAME=""  # Example: "privacera.yourdomain.com"

# ARN of the AWS Certificate Manager (ACM) certificate to use with the ALB.
CERTIFICATE_ARN="" # Example: "arn:aws:acm:us-east-1:1223444:certificate/622eb4db-ea45b48"

# Subnets in which the ALB will be deployed. Comma-separated list of subnet IDs.
SUBNETS=""  # Example: "subnet-1234abcd,subnet-5678efgh"

# Group name for the ALB. Used for grouping ALBs within a cluster.
AWS_ALB_GROUP="privacera-group"  # Example: "privacera-group"

# AWS Route 53 settings
# AWS Zone ID for the Route 53 hosted zone.
PRIVACERA_AWS_ZONE_ID=""  # Example: "Z3M3LMPEXAMPLE"

# Ranger Plugin configuration
# Set to true if the Network Load Balancer (NLB) for the Ranger plugin should be internal.
AWS_NLB_RANGER_INTERNAL="true"  # Example: "true" or "false"

# Optional settings

# Security groups to associate with the ALB. Comma-separated list of security group IDs.
#SECURITY_GROUPS=""  # Example: "sg-0123456789abcdef,sg-9876543210fedcba" (Optional)


